### ISSUE TITLE
Could not compile proc-macro2

### ISSUE THREAD

**Issue by adityac8** [mgattozzi/wasm-add#1]
I was following this [tutorial](https://rust-lang-nursery.github.io/rust-wasm/wasm-pack/rust-code.html) and when I run 
```
cargo test
```
The following error comes
```
error[E0433]: failed to resolve. Could not find `Group` in `proc_macro`
   --> C:\Users\aditya\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.3.8\src\unstable.rs:122:45
    |
122 |                 let mut group = proc_macro::Group::new(delim, tt.stream.inner.unwrap_nightly());
    |                                             ^^^^^ Could not find `Group` in `proc_macro`

error[E0433]: failed to resolve. Could not find `Op` in `proc_macro`
   --> C:\Users\aditya\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.3.8\src\unstable.rs:131:42
    |
131 |                 let mut op = proc_macro::Op::new(tt.op(), spacing);
    |                                          ^^ Could not find `Op` in `proc_macro`

error[E0433]: failed to resolve. Could not find `token_stream` in `proc_macro`
   --> C:\Users\aditya\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.3.8\src\unstable.rs:191:25
    |
191 |     Nightly(proc_macro::token_stream::IntoIter),
    |                         ^^^^^^^^^^^^ Could not find `token_stream` in `proc_macro`

error[E0554]: #![feature] may not be used on the stable release channel
  --> C:\Users\aditya\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.3.8\src\lib.rs:47:34
   |
47 | #![cfg_attr(feature = "nightly", feature(proc_macro))]
   |                                  ^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `proc-macro2`.
```
Am I doing something wrong?

**Comment by mgattozzi** [comment]
Just to make sure are you using `nightly` rust?

**Comment by adityac8** [comment]
I installed rust using the [link](https://win.rustup.rs/x86_64) and used the default options. I'm on a Windows Machine.

**Comment by mgattozzi** [comment]
You're not using nightly so this will fail. The tutorial starts [here](https://rust-lang-nursery.github.io/rust-wasm/wasm-pack/setup.html) and mentions you'll need nightly rust which can be shown how to be done [here](https://rust-lang-nursery.github.io/rust-wasm/setup.html).

But since you already have `rustup` installed try this in the directory for this program:

``` bash
# Install nightly
$ rustup install nightly

# Install wasm32-unknown-unknown
$ rustup target add wasm32-unknown-unknown --toolchain nightly

# Sets nightly for the current directory only
$ rustup override set nightly

# If you want nightly to be set globaly
$ rustup default nightly
```

Then try again.

**Comment by adityac8** [comment]
I followed the instructions above but was still getting an error. I added
```
#![feature(wasm_custom_section)]
```
and now it works.

**Comment by mgattozzi** [comment]
Can you put this in at the top as well

```
#![feature(wasm_import_module)]
```

And if you're using wasm-bindgen 0.1 in the Cargo.toml it should be 0.2. Change that and run

```
cargo update
```

Last but not least make sure the newest version of wasm-bindgen-cli is installed:

```
cargo install wasm-bindgen --force
```

Let me know if that works as that is what I did locally to get it working

**Comment by adityac8** [comment]
Hey @mgattozzi 
On running
```
cargo install wasm-bindgen
```
the following error comes
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing wasm-bindgen v0.2.8
error: specified package has no binaries
```
I have searched in Google and I think I should update my `Cargo.toml` file.

**Comment by adityac8** [comment]
Thanks @mgattozzi That works.

**Comment by adityac8** [comment]
Hey @mgattozzi Should I update all the changes made in this [commit](https://github.com/mgattozzi/wasm-add/commit/8f7865b30f29d6e81bfa43692326d66bf2aa38fc) on this [repo](https://github.com/rust-lang-nursery/rust-wasm).

**Comment by mgattozzi** [comment]
Yes please do. I'll open up an issue on the repo and assign you and close this one
